app:
  affiche_today:
    monday:
      '00-24': ['others']
    sunday:
      '11-14': ['exhibitions']
  actual_organizations:
    monday: &day
      '00-24':
        breakfast:
          options:
            meal_offer: завтраки
        coffe_house:
          options:
            meal_category: кофейни
        food_delivery:
          options:
            meal_category: доставка готовых блюд
    tuesday:
      <<: *day
    wednesday:
      <<: *day
    thursday:
      <<: *day
    friday:
      <<: *day
    saturday:
      <<: *day
    sunday:
      <<: *day
